// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://njgtazruxbmyitstqsaj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5qZ3RhenJ1eGJteWl0c3Rxc2FqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc0NDYyMjYsImV4cCI6MjA2MzAyMjIyNn0.5Cgc8xcm68F111w-QQGNGxAPkVL_p6MSdC2oUl9qzRw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);